(function() {var implementors = {};
implementors["node_primitives"] = [{"text":"impl Eq for TokenSymbol","synthetic":false,"types":[]},{"text":"impl Eq for CurrencyId","synthetic":false,"types":[]}];
implementors["node_runtime"] = [{"text":"impl Eq for SessionKeys","synthetic":false,"types":[]},{"text":"impl Eq for Runtime","synthetic":false,"types":[]},{"text":"impl Eq for Event","synthetic":false,"types":[]},{"text":"impl Eq for OriginCaller","synthetic":false,"types":[]},{"text":"impl Eq for Call","synthetic":false,"types":[]}];
implementors["pallet_robonomics_datalog"] = [{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Event&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Eq for Pallet&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Call&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_datalog_xcm"] = [{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Event&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Eq for Pallet&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Call&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_digital_twin"] = [{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Event&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Eq for Pallet&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Call&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_launch"] = [{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Event&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Eq for Pallet&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Call&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_launch_xcm"] = [{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Event&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Eq for Pallet&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Call&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_liability"] = [{"text":"impl&lt;T:&nbsp;Eq, E:&nbsp;Eq, V:&nbsp;Eq, A:&nbsp;Eq, I:&nbsp;Eq&gt; Eq for SignedLiability&lt;T, E, V, A, I&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: Technical,<br>&nbsp;&nbsp;&nbsp;&nbsp;E: Economical,<br>&nbsp;&nbsp;&nbsp;&nbsp;V: Verify&lt;Signer = A&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;A: IdentifyAccount&lt;AccountId = I&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;I: Parameter,<br>&nbsp;&nbsp;&nbsp;&nbsp;T::Parameter: Eq,<br>&nbsp;&nbsp;&nbsp;&nbsp;E::Parameter: Eq,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Event&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Eq for Pallet&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Call&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_rws"] = [{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Event&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; Eq for Pallet&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Config&gt; Eq for Call&lt;T&gt;","synthetic":false,"types":[]}];
implementors["parachain_runtime"] = [{"text":"impl Eq for SessionKeys","synthetic":false,"types":[]},{"text":"impl Eq for Runtime","synthetic":false,"types":[]},{"text":"impl Eq for Event","synthetic":false,"types":[]},{"text":"impl Eq for OriginCaller","synthetic":false,"types":[]},{"text":"impl Eq for Call","synthetic":false,"types":[]}];
implementors["robonomics_protocol"] = [{"text":"impl Eq for Message","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Eq + Datalog&gt; Eq for RecordCall&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T::Record: Eq,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Eq + Datalog&gt; Eq for NewRecordEvent&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T::Record: Eq,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Eq + Datalog&gt; Eq for EreaseCall&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Eq + Datalog&gt; Eq for ErasedEvent&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;'a, T:&nbsp;Eq + Datalog&gt; Eq for DatalogStore&lt;'a, T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Eq + Launch&gt; Eq for LaunchCall&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T::AccountId: Eq,<br>&nbsp;&nbsp;&nbsp;&nbsp;T::Parameter: Eq,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Eq + Launch&gt; Eq for NewLaunchEvent&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T::Parameter: Eq,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl Eq for Robonomics","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()