(function() {var implementors = {};
implementors["ipci_runtime"] = [{"text":"impl Copy for Runtime","synthetic":false,"types":[]}];
implementors["pallet_robonomics_datalog"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_launch"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_liability"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_robonomics_rws"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["robonomics_parachain_runtime"] = [{"text":"impl Copy for Runtime","synthetic":false,"types":[]}];
implementors["robonomics_runtime"] = [{"text":"impl Copy for Runtime","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()